// Re-export the compiled contract wrapper for use by other packages
// The actual wrapper is generated by the Tact compiler during build
// and lives at build/JettonEscrow/tact_JettonEscrow.ts

export {
    JettonEscrow,
    type EscrowData,
} from '../build/JettonEscrow/tact_JettonEscrow';
